name: CI for Vue Project

# Define quando o workflow deve ser executado
on:
  push:
    branches:
      - main  # Executa o workflow em push na branch "main"
  pull_request:
    branches:
      - main  # Executa o workflow em pull requests para a branch "main"

# Definição dos jobs
jobs:
  build:

    # Sistema operacional e versão Node.js
    runs-on: ubuntu-latest

    # Estratégia para a versão 20 do Node.js
    strategy:
      matrix:
        node-version: [20.x]  # Usando apenas a versão mais recente e suportada do Node.js

    steps:
      # Checa o repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Configura o Node.js e instala dependências
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      # Executa os testes do projeto
      - name: Run tests
        run: npm run test

      # Gera a build do projeto
      - name: Build project
        run: npm run build
